// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: internal/local/local.proto

package local

import (
	protos "github.com/ServiceWeaver/weaver/runtime/protos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListenState contains the state stored for the network listeners in the store.
type ListenState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Listeners is the set of all exported listeners in the deployment.
	Listeners []*protos.Listener `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
}

func (x *ListenState) Reset() {
	*x = ListenState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_local_local_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenState) ProtoMessage() {}

func (x *ListenState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_local_local_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenState.ProtoReflect.Descriptor instead.
func (*ListenState) Descriptor() ([]byte, []int) {
	return file_internal_local_local_proto_rawDescGZIP(), []int{0}
}

func (x *ListenState) GetListeners() []*protos.Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

var File_internal_local_local_proto protoreflect.FileDescriptor

var file_internal_local_local_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x1a, 0x23, 0x77, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x6c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x65,
	0x61, 0x76, 0x65, 0x72, 0x2f, 0x77, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6b, 0x65, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_local_local_proto_rawDescOnce sync.Once
	file_internal_local_local_proto_rawDescData = file_internal_local_local_proto_rawDesc
)

func file_internal_local_local_proto_rawDescGZIP() []byte {
	file_internal_local_local_proto_rawDescOnce.Do(func() {
		file_internal_local_local_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_local_local_proto_rawDescData)
	})
	return file_internal_local_local_proto_rawDescData
}

var file_internal_local_local_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_local_local_proto_goTypes = []interface{}{
	(*ListenState)(nil),     // 0: local.ListenState
	(*protos.Listener)(nil), // 1: runtime.Listener
}
var file_internal_local_local_proto_depIdxs = []int32{
	1, // 0: local.ListenState.listeners:type_name -> runtime.Listener
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_local_local_proto_init() }
func file_internal_local_local_proto_init() {
	if File_internal_local_local_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_local_local_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_local_local_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_local_local_proto_goTypes,
		DependencyIndexes: file_internal_local_local_proto_depIdxs,
		MessageInfos:      file_internal_local_local_proto_msgTypes,
	}.Build()
	File_internal_local_local_proto = out.File
	file_internal_local_local_proto_rawDesc = nil
	file_internal_local_local_proto_goTypes = nil
	file_internal_local_local_proto_depIdxs = nil
}
