[serviceweaver]
binary = "./echo"

[single]
listeners.echo = {address = "localhost:9000"}

[multi]
listeners.echo = {address = "localhost:9000"}

[gke]
regions = ["us-west1"]
listeners.echo = {is_public=true, hostname = "echo.example.com"}
