// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: internal/store/store.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetProto contains the set of elements stored under a key in the store.
type SetProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements [][]byte `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *SetProto) Reset() {
	*x = SetProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_store_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProto) ProtoMessage() {}

func (x *SetProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProto.ProtoReflect.Descriptor instead.
func (*SetProto) Descriptor() ([]byte, []int) {
	return file_internal_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *SetProto) GetElements() [][]byte {
	if x != nil {
		return x.Elements
	}
	return nil
}

// SequenceProto contains a sequence of unique values.
type SequenceProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sequence maps a value to its index in the sequence. For example, if we
	// sequenced "a", "b", and "c" in order, then "a" maps to 0, "b" maps to 1,
	// and "c" maps to 2.
	Sequence map[string]int64 `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *SequenceProto) Reset() {
	*x = SequenceProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_store_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SequenceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceProto) ProtoMessage() {}

func (x *SequenceProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceProto.ProtoReflect.Descriptor instead.
func (*SequenceProto) Descriptor() ([]byte, []int) {
	return file_internal_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *SequenceProto) GetSequence() map[string]int64 {
	if x != nil {
		return x.Sequence
	}
	return nil
}

var File_internal_store_store_proto protoreflect.FileDescriptor

var file_internal_store_store_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x22, 0x26, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x0d,
	0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3e, 0x0a,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x3b, 0x0a,
	0x0d, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x57, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2f, 0x77, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6b,
	0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_store_store_proto_rawDescOnce sync.Once
	file_internal_store_store_proto_rawDescData = file_internal_store_store_proto_rawDesc
)

func file_internal_store_store_proto_rawDescGZIP() []byte {
	file_internal_store_store_proto_rawDescOnce.Do(func() {
		file_internal_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_store_store_proto_rawDescData)
	})
	return file_internal_store_store_proto_rawDescData
}

var file_internal_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_store_store_proto_goTypes = []interface{}{
	(*SetProto)(nil),      // 0: store.SetProto
	(*SequenceProto)(nil), // 1: store.SequenceProto
	nil,                   // 2: store.SequenceProto.SequenceEntry
}
var file_internal_store_store_proto_depIdxs = []int32{
	2, // 0: store.SequenceProto.sequence:type_name -> store.SequenceProto.SequenceEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_store_store_proto_init() }
func file_internal_store_store_proto_init() {
	if File_internal_store_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_store_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_store_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SequenceProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_store_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_store_store_proto_goTypes,
		DependencyIndexes: file_internal_store_store_proto_depIdxs,
		MessageInfos:      file_internal_store_store_proto_msgTypes,
	}.Build()
	File_internal_store_store_proto = out.File
	file_internal_store_store_proto_rawDesc = nil
	file_internal_store_store_proto_goTypes = nil
	file_internal_store_store_proto_depIdxs = nil
}
